# Generated by Django 3.0.3 on 2020-03-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateTimeField(verbose_name='week ending')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
